version: '3.7'

services:
  ccc:
    build: .
    image: konstantinschulz/covid-credibility-classifier:v1
#    ports:
#      - "8000:8000"
  gbert_base_fang_covid:
    build: ./streamlit_app
    image: konstantinschulz/gbert_base_fang_covid:latest
